
[TagConfig]
	#A list of mod ids sorted by preference when getting an Item for a tag
	ITEM_PREFERENCE = ["minecraft", "alltheores", "thermal", "create", "mekanism", "kubejs", "appliedenergistics2", "botania", "quark"]

