
["Ignored Mods"]
	#Client-side mod IDs that will be ignored if not present on the server.
	clientIgnoredMods = ["worldedit", "jeresources", "advancementplaques", "equipmentcompare"]
	#Server-side mod IDs that will not be sent to the client.
	serverIgnoredMods = ["worldedit"]

[Buffer]
	#New size of server compatibility packet buffer, in bytes.
	#Default: 100000
	#Range: > 32767
	newPaketBufferSize = 100000

