storagenetwork = true
tconstruct = true
fastfurnaceminusreplacement = true
sophisticatedbackpacks = true
fastfurnace = true
craftingstation = true
ironfurnaces = true
occultism = true
jei = true
extendedcrafting = true
fastbenchminusreplacement = true
refinedstorageaddons = true
craftingcraft = true
toms_storage = true
refinedstorage = true
prettypipes = true
fastbench = true
appliedenergistics2 = false
cyclic = true

